### ISSUE TITLE
Missing lib folder

### ISSUE THREAD

**Issue by JohnDuke259** [GIScience/helios#21]
Hello folks,

I got to know about HELIOS recently and I have been trying to build it in my Ubuntu computer following the link on https://github.com/GIScience/helios/wiki/Howto:-Build-HELIOS-with-Eclipse-and-Maven. The lib folder and jar files stated in the tutorial are not there am unable to build it

Any help would be appreciated.

Thanks

**Comment by komazsofi** [comment]
Hi,

Switch to the developer branch there is a new way to install the software. https://github.com/GIScience/helios/tree/developer . 

And may pay attention to download the right branch.

Best,
Zsofi

**Comment by JohnDuke259** [comment]
Thank you so much for your quick reply and help. I will try that and let you know how it goes.

Best regards
John

**Comment by JohnDuke259** [comment]
Many thanks for your help. I have installed it.

Best regards
