### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by lesleydavidson6** [GIScience/helios#28]
Hello,
I'm hoping to use Helios to help me plan UAV lidar. I'm having issues building Helios. I have added the Java Build Path for jre1.8.0_31. I also managed to add lemur-1.9.1.jar using Add External JARs...The Java Compiler compliance level is set to 1.8. However, lidar is not recognized when I search for it in run as java application. I'm not certain where I've gone wrong. Also, the library folder seems to be missing from the github download. I ended up copying it from the pre-compiled folder. Thanks very much for your help

**Comment by kathapand** [comment]
Hi! Could you try doing the compilation with maven? That is the either way if you just need it compiled. According to the readme:
https://github.com/GIScience/helios/blob/master/README.md#install
We'll check what the problem with the eclipse setup could be, thanks for the message!
