### ISSUE TITLE
ULS simulated

### ISSUE THREAD

**Issue by ShuangnaJin** [GIScience/helios#30]
In using HELIOS, I encountered the following questions:
1. When I simulated the ULS data using the platform of quadcopter and RIEGL VUX-1UAV scanner, scanning stopped after the flight of the first scanning line, but using the platform sr22 can scan all 6 airlines. Why?
(Attachment is my xml file)
2.The beam origin of the scanner "RIEGL VUX-1UAV" is the same as "Optech ALTM 2033"? And what does the "beam origin" mean?
3.How is the platform's coordinate system and where is the 0° of the sensor scanning angle? As my first scanning line output, it had only a little points, from the Jmonkey simulator, I found the emitted laser can hardly hit the ground.

**Comment by kathapand** [comment]
Hi ShuangnaJin,
I think the xml file is not attached? But to compare your specifications to an existing ULS simulation, you might check this repository: 

> Hämmerle, Martin; Lukač, Niko; Chen, Kuei-Chia; Koma, Zsófia; Wang, Chi-Kuei; Anders, Katharina; Höfle, Bernhard, 2017, "HELIOS full-waveform laser scanning simulation framework. Source code, precompiled version, example files for study of understory tree height scanning and respective output.", https://doi.org/10.11588/data/10101, heiDATA, V1 

The beam origin is the position at which the laser beam originates from the sensor, relative to the 3D model (visModel, e.g. "scanners/vux-1uav/vux-1uav.obj").
The 0° of the sensor scanning angle should be normal/orthogonal to the position of the beam origin on the sensor - but consider the orientation of the sensor when specified in the rotation of the beam origin.

**Comment by kathapand** [comment]
I will close this issue as it is inactive and therefore assumingly does not persist.
