### ISSUE TITLE
Could the author provide an illustration picture for scanner settings?

### ISSUE THREAD

**Issue by ludwig1860** [GIScience/helios#34]
Hi, 
I come here from DART LiDAR module because the DART requires much too high performance of computer and takes a lot of time for simulating TLS measurement of forest sample plot with 0.036 degree resolution.

Really nice job, the HELIOS. Perfectly fit my need. **Less parameters and faster simulation as well as visualization**. But the only one I could say is **the lack of illustration of scanner parameters and scene parameters**, such as `scan angle`, `pulse frequency `, `scan frequency `, `yaw`, `pitch` and `roll`. 

+ `scan angle`: is the range of scan angle is 0~90 degrees? I saw you said that it is defined as the half of FOV in zenith direction, e.g., if `scan angle = 90`, the FOV will be 180 degrees, implying measurement from downward to upward?
+  `pitch` : the default value is 90 degrees. Are the  `yaw`, `pitch` and `roll` of tree model consistent with those of airplane? I tested `yaw` and found its meaningful range is 0~90. Might be not. Could you explain a little?

**Comment by ludwig1860** [comment]
I noticed you had answered another question about `scan angle` setting.
> Now is possible to set the vertical field of view of the scanning. For this, go to the survey XML and add on each `<scannerSettings>` the desired min and max values with `verticalAngleMin_deg="angle"`,` verticalAngleMax_deg="angle"`. The scan angle range is set automatically by reading those min and max.  This example shows how to set the vertical FOV to (-5º, 25º):
If I have a good memory, you explain `scan angle = half FOV` in some webpage. However, it seems to be conflicted with the above words.

**Comment by kathapand** [comment]
Hello,
I have added a small but visual [explanation of the FOV settings in the wiki](https://github.com/GIScience/helios/wiki/Manual#defining-the-horizontal-and-vertical-field-of-view-fov). 
The pulse frequency should be set according to the "planned survey" with the used system. The headRotatePerSec_deg and scanFreq_hz must be adjusted for the target resolution. We recognize that this is a bit of a detour in the parametrization for the user in the current implementation. This way of implementation is chosen to reconstruct the "inner working" of the laserscanning sensor as closely as possible. 
For the rotation of the sceneparts, this should be the "common" axes and work for the full 360° range. I did a quick test on some primitive shapes with a helping figure:
![scene_roll_pitch_yaw](https://user-images.githubusercontent.com/33595918/80986642-23008600-8e31-11ea-9655-619c4cfa451a.png)
I think the reason the "Betula_pendula_1.obj" needs to be rotated by 90° to be upwards, is that the model itself is not pointing upwards (similar to the arbaro demo models). When loading into, e.g. [CloudCompare](www.cloudcompare.org), it is "lying on the side". Thus, the pitch rotation by 90° in HELIOS orientates it upwards like a tree. I guess then other rotations are difficult to see through intuitively with these rotated axes - might be easiest to correct the general orientation of the obj outside HELIOS and then tweak the yaw (rotation around z-axis) for different versions in the scene.
I hope it helps - thanks for the feedback!
Katharina

**Comment by ludwig1860** [comment]
Hi, Katharina,
No doubt, it helps me.
I corrected the orientation of obj-file to the common-use orientation in real 3D scene. Then, the orientation parameters (`pitch`, `roll`, `yaw`) in XML file were adjusted intuitively. To keep tree upward, `pitch` and `roll` are both always `0`. User can adjust `yaw` in the range of 0-360 degrees. 

> Here is a forest example with three trees and four TLS scans. 
+ Tree A: `pitch=0`, `roll=0`, `yaw=90`;
+ Tree B: `pitch=0`, `roll=0`, `yaw=265`;
+ Tree C: `pitch=0`, `roll=0`, `yaw=155`;
and for the TLS scans, `onGround=false` and `z=0`.

[![forest scenario](https://s1.ax1x.com/2020/05/05/YPv858.png)](https://imgchr.com/i/YPv858)

The explanation of FOV and other parameters are amazing. I believe it will help a lot for other users. I hope you don't mind I cite the picture here, for other users' convenience.

![explanation of scanner setting](https://s1.ax1x.com/2020/05/05/YPxZd0.png)

Hope HELIOS become better and better.

Linyuan

**Comment by ludwig1860** [comment]
Hi, Katharina,
I found another small bug in the operation of TLS simulation. 
+ When I used `verticalAngleMin_deg` and `verticalAngleMax_deg` mode, the TLS scanner did NOT start to scan (the red laser beam didn't move and no points outputted), e.g.,  `verticalAngleMin_deg=-60.0` and `verticalAngleMax_deg=90.0`.
+  When I used `scanAngle_deg` mode, everything is normal, e.g., `scanAngle_deg=90.0`.

Could you verify this problem and try to solve it? Usually, we prefer to use **min and max vertical angle** rather than **scan angle**, as you suggested.
Linyuan

**Comment by kathapand** [comment]
Right: The parameters `verticalAngleMin_deg` and `verticalAngleMax_deg` are currently only available in the developer branch. The information is added to the wiki.
You would specify the parameters following this scheme:
```
<leg>
    <platformSettings x="0.8566228596501162" y="25.587345982284987" z="-1.1102230246251565E-16" onGround="true" />
    <scannerSettings active="true" pulseFreq_hz="100000" scanAngle_deg="50.0" scanFreq_hz="120" headRotatePerSec_deg="10.0" headRotateStart_deg="128.91550582542592" headRotateStop_deg="223.45354343073828" verticalAngleMin_deg="-10.0" verticalAngleMax_deg="30.0" />
</leg>
```
The developer branch also contains some fixes, so it is suggested to use this for your simulations.
