### ISSUE TITLE
Introduce HELIOS platform and workflow in Chinese for extending impact

### ISSUE THREAD

**Issue by ludwig1860** [GIScience/helios#37]
Dear the authors and maintainers of HELIOS,

Hi.
I summarized the features, basic principles and usage workflows of HELIOS in Chinese language, to extend the impact of HELIOS, as it is a so powerful and useful application. I'd like to put the web link of the Chinese blogs (博客园) here, if you don't mind, for the convenience of Chinese researchers and users. 

+ The introduction of HELIOS: features, modules, basic principles. https://www.cnblogs.com/ludwig1860/p/12841890.html
+ The workflow of TLS simulation: an example of forest plot. https://www.cnblogs.com/ludwig1860/p/12849887.html

If it's not proper to post here, please tell me. Thank you for your understanding in advance.

Linyuan Li

**Comment by kathapand** [comment]
This is a nice suggestion and thank you for your effort!
