### ISSUE TITLE
set scannerWaveLength

### ISSUE THREAD

**Issue by dongdada896** [GIScience/helios#38]
Hi,
 I followed your instruction in helios/FWF.md to set the scannerWaveLength[ns] as 0.000005 in order to make Scanner's operating wavelength become 1550nm. But the console displays that the wavelength is still 1064nm.I don’t know why.
 Appreciate your help sincerely.

**Comment by jcsi2410** [comment]
I have the same question. Have you tried adding it to your survey.xml file?

**Comment by kathapand** [comment]
Hi! I am not sure about this setting, but you can add it to the instrument specification in the scanner-xml (TLS or ALS). See for example here: https://github.com/GIScience/helios/blob/master/data/scanners_tls.xml#L103

**Comment by dongdada896** [comment]
@kathapand 
I set up according to your instruction and it worked. But there will be a little problem, if you set wavelength_nm = "1550", the console will display Wavelength: 1549nm.

**Comment by dongdada896** [comment]
@kathapand 
I set up according to your instruction and it worked. But there will be a little problem, if you set wavelength_nm = "1550", the console will display Wavelength: 1549nm.
All in all, thank you very much for your help.

**Comment by dongdada896** [comment]
@jcsi2410

**Comment by jcsi2410** [comment]
@kathapand Thank you for your prompt response. I'd settle for the glitch also mentioned by @dongdada896 
![image](https://user-images.githubusercontent.com/67182979/85718134-90de7500-b731-11ea-9801-74e34ca617d2.png)

**Comment by jcsi2410** [comment]
I'd also like to confirm if all these parameters are meant to be added to the instrument specs. Cheers

![image](https://user-images.githubusercontent.com/67182979/85718367-caaf7b80-b731-11ea-8ec2-2ab4bb6a3f4e.png)

**Comment by kathapand** [comment]
Hi! It could be this is a rounding issue, looks like a bug that should be checked. Thanks for documenting the observation!
I tried to contact (both/either) of you directly, but cannot obtain contact information. Maybe you could send me a short email (https://github.com/kathapand), then I can write to you. It is an honest inquiry and info on HELIOS, but of course no problem if you prefer not to!

**Comment by lwiniwar** [comment]
closed as wont-fix (1 nm difference is probably insignificant and may just be a display issue)
