### ISSUE TITLE
Scan Settings - Pulse Frequency and Scan Frequency

### ISSUE THREAD

**Issue by KoeMai** [GIScience/helios#8]
I tried to understand some settings in the HELIOS GUI.

What is the different between Pulse Frequency and Scan Frequency?

**Comment by sebastian-bechtold** [comment]
_Pulse frequency_ is the number of laser pulses per time unit. Higher pulse frequency means higher scan resolution.

_Scan frequency_ is the number of scan lines (i.e. repetitions of the beam deflector's movement pattern) per time unit. Higher scan frequency means faster scanning at lower resolution (unless the pulse frequency is increased, too).
