### ISSUE TITLE
Use of scan angle

### ISSUE THREAD

**Issue by KoeMai** [GIScience/helios#9]
What influence does the Scan Angle has? 
Where in the simulation is it used?  
Is it the angle range of the defractor?
Is there a relation between Scan Angle and the highlighted ScanRange in the scanner visualization (lightblue)?

**Comment by KoeMai** [comment]
Is the scan angle for a TLS scanner, the vertical angle for sending out the pulses?

I tried it by changing the scan angle from 50° to 5°:
5°:
![bildschirmfoto von 2017-06-27 00-49-29](https://user-images.githubusercontent.com/21360085/27563562-c7e39396-5ad2-11e7-907f-81892f0d8ab1.png)
50°:
![bildschirmfoto von 2017-06-27 00-48-27](https://user-images.githubusercontent.com/21360085/27563566-cad9de5c-5ad2-11e7-8b43-a713eaa9c553.png)

Who defines the start and end scan angle? Scanner-XML?
How is the start and end scan angle defined?

**Comment by sebastian-bechtold** [comment]
Sorry, I was wrong. Yes, it is the _vertical_ scan angle, not the horizontal one. I updated my post above. The scan angle is defined in the survey XML in the element <scanner-settings>.

**Comment by KoeMai** [comment]
The scan angle defines the deflection of the beam by the mirror ( for VZ-400 the rotating mirror/polygnonMirror).

In the GUI is it possible to enter the scan angle in (Deg.), I think this field represents the maximum allowed scan angle with a zero scan angle offset. 
This means the scan angle of a single pulse will move from -scanAngle+scanAngleOffset  -> scanAngleOffset --> +scanAngle+scanAngleOffset.

Did I described the scan angle correct?

**Comment by sebastian-bechtold** [comment]
Yes, as far as I remember my own code, this is correct ;).
